version: '1.3'

services:
  faktenspeicher:
    container_name: faktenspeicher
    pull_policy: build
    build: .
    image: faktenspeicher:latest
    environment:
      - PYTHONUNBUFFERED=1
      - admin_login=$admin_login
      - admin_password=$admin_password
      - db_host=$db_host
      - db_port=$db_port
      - db_name=$db_name
      - db_user=$db_user
      - db_password=$db_password

    ports:
      - 8501:8501
